Repository CECS-491A/SSO, pull requests merged in 2019-03, with the labels that each got.

#24 Feature/login
  Backend/DataAccessLayer/DataAccessLayer.csproj
  Backend/DataAccessLayer/Migrations/201903100743056_create-attribute-incorrectPasswordCount.Designer.cs
  Backend/DataAccessLayer/Migrations/201903100743056_create-attribute-incorrectPasswordCount.cs
  Backend/DataAccessLayer/Migrations/201903100743056_create-attribute-incorrectPasswordCount.resx
  Backend/DataAccessLayer/Models/LoginRequest.cs
  Backend/DataAccessLayer/Models/User.cs
  Backend/KFC-WebAPI/App_Start/WebApiConfig.cs
  Backend/KFC-WebAPI/Controllers/UsersController.cs
  Backend/KFC-WebAPI/KFC-WebAPI.csproj
  Backend/ManagerLayer/Login/LoginManager.cs
  Backend/ManagerLayer/ManagerLayer.csproj
  Backend/UnitTesting/LoginManagerUT.cs
  Backend/UnitTesting/UnitTesting.csproj
  Backend/UnitTesting/UsersControllerUT.cs
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/components/NavBar.vue
  Frontend/src/router.js
  Frontend/src/views/Dashboard.vue
  Frontend/src/views/Login.vue
Labels: feature

#23 Feature/Auto-App-Sync: App Registration
  Backend/DataAccessLayer/DataAccessLayer.csproj
  Backend/DataAccessLayer/Database/dbContext.cs
  Backend/DataAccessLayer/Migrations/201903070039162_create-tables-applications-apikeys.Designer.cs
  Backend/DataAccessLayer/Migrations/201903070039162_create-tables-applications-apikeys.cs
  Backend/DataAccessLayer/Migrations/201903070039162_create-tables-applications-apikeys.resx
  Backend/DataAccessLayer/Models/ApiKey.cs
  Backend/DataAccessLayer/Models/Application.cs
  Backend/DataAccessLayer/Repositories/ApiKeyRepository.cs
  Backend/DataAccessLayer/Repositories/ApplicationRepository.cs
  Backend/Dev/App.config
  Backend/KFC-WebAPI/Controllers/ApplicationController.cs
  Backend/KFC-WebAPI/Controllers/ResetController.cs
  Backend/KFC-WebAPI/KFC-WebAPI.csproj
  Backend/KFC-WebAPI/Properties/PublishProfiles/CustomProfile.pubxml
  Backend/KFC-WebAPI/Properties/PublishProfiles/CustomProfile1.pubxml
  Backend/KFC-WebAPI/Properties/PublishProfiles/FolderProfile.pubxml
  Backend/ManagerLayer/AccessControl/AuthorizationManager.cs
  Backend/ManagerLayer/App.config
  Backend/ManagerLayer/ApplicationManagement/ApplicationManager.cs
  Backend/ManagerLayer/ApplicationManagement/ApplicationRequest.cs
  Backend/ManagerLayer/ApplicationManagement/HttpResponseContent.cs
  Backend/ManagerLayer/ManagerLayer.csproj
  Backend/ManagerLayer/UserManagement/UserManagementManager.cs
  Backend/ServiceLayer/ServiceLayer.csproj
  Backend/ServiceLayer/Services/ApiKeyService.cs
  Backend/ServiceLayer/Services/ApplicationService.cs
  Backend/ServiceLayer/Services/IApiKeyService.cs
  Backend/ServiceLayer/Services/IApplicationService.cs
  Backend/ServiceLayer/Services/TokenService.cs
  Backend/UnitTesting/ApiKeyServiceUT.cs
  Backend/UnitTesting/App.config
  Backend/UnitTesting/ApplicationManagerUT.cs
  Backend/UnitTesting/ApplicationServiceUT.cs
  Backend/UnitTesting/TestingUtils.cs
  Backend/UnitTesting/UnitTesting.csproj
  Backend/UnitTesting/UserServiceUT.cs
  Backend/UpgradeLog2.htm
  Backend/UpgradeLog3.htm
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/components/NavBar.vue
  Frontend/src/main.js
  Frontend/src/router.js
  Frontend/src/views/AppDelete.vue
  Frontend/src/views/AppRegister.vue
  Frontend/src/views/GenerateKey.vue
Labels: feature

#25 Feature/register
  Backend/KFC-WebAPI/Controllers/UsersController.cs
  Backend/ManagerLayer/AuthorizationManager.cs
  Backend/ManagerLayer/ManagerLayer.csproj
  Backend/ManagerLayer/UserManager.cs
  Backend/ServiceLayer/Exceptions.cs
  Backend/ServiceLayer/ServiceLayer.csproj
  Backend/ServiceLayer/Services/UserService.cs
  Backend/WebAPI/Web.config
  Backend/WebAPI/WebAPI.csproj
  Backend/WebAPI/packages.config
  Frontend/package-lock.json
  Frontend/src/components/NavBar.vue
  Frontend/src/router.js
  Frontend/src/services/request.js
  Frontend/src/views/Register.vue
Labels: feature

#30 Feature/auto app sync
  Backend/DataAccessLayer/DataAccessLayer.csproj
  Backend/DataAccessLayer/Migrations/201903160219313_update-applications-add-SharedSecretKey.Designer.cs
  Backend/DataAccessLayer/Migrations/201903160219313_update-applications-add-SharedSecretKey.cs
  Backend/DataAccessLayer/Migrations/201903160219313_update-applications-add-SharedSecretKey.resx
  Backend/DataAccessLayer/Models/Application.cs
  Backend/DataAccessLayer/Repositories/ApiKeyRepository.cs
  Backend/DataAccessLayer/Repositories/ApplicationRepository.cs
  Backend/KFC_WebAPI/Controllers/ApplicationController.cs
  Backend/ManagerLayer/ApplicationManagement/ApplicationManager.cs
  Backend/ManagerLayer/ApplicationManagement/HttpResponseContent.cs
  Backend/ServiceLayer/ServiceLayer.csproj
  Backend/ServiceLayer/Services/ApiKeyService.cs
  Backend/ServiceLayer/Services/ApplicationService.cs
  Backend/ServiceLayer/Services/IApiKeyService.cs
  Backend/ServiceLayer/Services/IApplicationService.cs
  Backend/UnitTesting/ApiKeyServiceUT.cs
  Backend/UnitTesting/ApplicationManagerUT.cs
  Backend/UnitTesting/ApplicationServiceUT.cs
  Frontend/package-lock.json
  Frontend/src/main.js
  Frontend/src/views/AppRegister.vue
  documents/Auto App Sync/SSO_ Automated App Sync Design Doc.pdf
  documents/Auto App Sync/SSO_ Automated App Sync Test Plan.pdf
  documents/Auto App Sync/SSO_ Automated App Sync User Manual.pdf
Labels: chore

#54 E2E screenshot tests
  .gitignore
  Backend/UnitTesting/TestingUtils.cs
  E2E/Auto App Sync/ScreenshotTest.js
  E2E/package-lock.json
Labels: awaiting merge

#56 E2e test registration
  Backend/ServiceLayer/Services/PasswordService.cs
  Backend/UnitTesting/SessionServiceUT.cs
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/views/Register.vue
  Frontend/test/register.test.e2e.js
  Frontend/test/util.e2e.js
Labels: awaiting merge

#45 added db config for release
  Backend/DataAccessLayer/DataAccessLayer.csproj
  Backend/DataAccessLayer/Database/dbContext.cs
Labels: DO NOT MERGE

#58 Add loading dialogue to registration
  Backend/ManagerLayer/AuthorizationManagement/AuthorizationManager.cs
  Backend/UnitTesting/AuthorizationManagerUT.cs
  Backend/UnitTesting/PasswordServiceUT.cs
  Backend/UnitTesting/TestingUtils.cs
  Backend/UnitTesting/UnitTesting.csproj
  Frontend/package.json
  Frontend/src/views/Register.vue
  Frontend/test/register.test.e2e.js
Labels: awaiting merge
