Repository CECS-491A/SSO, pull requests merged in 2019-04, with the labels that each got.

#51 Login UI Changes
  Backend/KFC_WebAPI/Controllers/UsersController.cs
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/components/NavBar.vue
  Frontend/src/services/request.js
  Frontend/src/views/Login.vue
  Frontend/src/views/Register.vue
Labels: awaiting merge

#57 Feature/dashboard display apps
  Frontend/.env.production
  Frontend/src/components/Dialogs/AppInfo.vue
  Frontend/src/components/Dialogs/Loading.vue
  Frontend/src/views/Dashboard.vue
Labels: awaiting changes

#48 feature/password-reset-and-update
  Backend/DataAccessLayer/DataAccessLayer.csproj
  Backend/DataAccessLayer/Database/dbContext.cs
  Backend/DataAccessLayer/Migrations/201904021012527_upate-passwordresets-modify-table.Designer.cs
  Backend/DataAccessLayer/Migrations/201904021012527_upate-passwordresets-modify-table.cs
  Backend/DataAccessLayer/Migrations/201904021012527_upate-passwordresets-modify-table.resx
  Backend/DataAccessLayer/Models/PasswordReset.cs
  Backend/DataAccessLayer/Repositories/ResetRepository.cs
  Backend/DataAccessLayer/Requests/NewPasswordRequest.cs
  Backend/DataAccessLayer/Requests/SecurityAnswersRequest.cs
  Backend/DataAccessLayer/Requests/SendResetEmailRequest.cs
  Backend/DataAccessLayer/Requests/UpdatePasswordRequest.cs
  Backend/KFC_WebAPI/Controllers/ResetController.cs
  Backend/KFC_WebAPI/Controllers/UsersController.cs
  Backend/ManagerLayer/ApplicationManagement/ApplicationManager.cs
  Backend/ManagerLayer/PasswordManagement/PasswordManager.cs
  Backend/ServiceLayer/Services/EmailService.cs
  Backend/ServiceLayer/Services/IEmailService.cs
  Backend/ServiceLayer/Services/ResetService.cs
  Backend/UnitTesting/EmailServiceUT.cs
  Backend/UnitTesting/PasswordManagerUT.cs
  Backend/UnitTesting/ResetPasswordUT.cs
  Backend/UnitTesting/TestingUtils.cs
  Frontend/src/assets/KFC_Logo_v2.png
  Frontend/src/components/NavBar.vue
  Frontend/src/router.js
  Frontend/src/views/Home.vue
  Frontend/src/views/Login.vue
  Frontend/src/views/ResetPassword.vue
  Frontend/src/views/SendResetLink.vue
  Frontend/src/views/UpdatePassword.vue
Labels: awaiting changes

#93 Refactored PasswordReset files to use a single database context
  Backend/DataAccessLayer/DataAccessLayer.csproj
  Backend/DataAccessLayer/Repositories/ResetRepository.cs
  Backend/DataAccessLayer/RequestModels/NewPasswordRequest.cs
  Backend/DataAccessLayer/RequestModels/SecurityAnswersRequest.cs
  Backend/DataAccessLayer/RequestModels/SendResetEmailRequest.cs
  Backend/DataAccessLayer/RequestModels/UpdatePasswordRequest.cs
  Backend/KFC_WebAPI/Controllers/ResetController.cs
  Backend/KFC_WebAPI/Controllers/UsersController.cs
  Backend/ManagerLayer/PasswordManagement/PasswordManager.cs
  Backend/ServiceLayer/Services/IResetService.cs
  Backend/ServiceLayer/Services/ResetService.cs
  Backend/UnitTesting/PasswordResetManagerUT.cs
  Backend/UnitTesting/PasswordResetServiceUT.cs
Labels: chore
